name: Mumble Server
version: 0.1.0-beta5
slug: mumble_server
description: >
  A Mumble server to run alongside home assistant. Allows private voice
  communication between Mumble clients.
arch:
  - amd64
  - armv7
url: https://github.com/lzulauf/hassio-addon-mumble-server
startup: services
boot: auto
ports:
  64738/tcp: 64738
  64738/udp: 64738
ports_description:
  64738/tcp: Mumble server connect port
  64738/udp: Mumble server communicate port
stage: experimental
options:
  welcometext: "<br />Welcome to this server running <b>Murmur</b>.<br />Enjoy your stay!<br />"
  serverpassword: ""
schema: 
  welcometext: str
  serverpassword: str
